import { Property, TourRequest, SellerLead, AgentProfile } from './types';

export const agentProfiles: AgentProfile[] = [
  { id: 'pracheta', name: 'Pracheta', role: 'Lead Operations Advisor', initial: 'P' },
  { id: 'mohith', name: 'Mohith Sindhia', role: 'Managing Broker', initial: 'M' },
  { id: 'shyam', name: 'Shyam', role: 'Partner & Tech Liaison', initial: 'S' },
  { id: 'aryan', name: 'Aryan', role: 'Client Relations Manager', initial: 'A' }
];

export const defaultProperties: Property[] = [
  {
    id: 1,
    title: "Evergreen Foothills Family Home",
    neighborhood: "Evergreen",
    price: 1450000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    type: "House",
    status: "Buy",
    school_rating: 9,
    school_details: "Evergreen Elementary, Chaboya Middle, Evergreen Valley High (9/10)",
    commute_times: { apple: 25, google: 28, nvidia: 20, adobe: 15 },
    solar: true,
    ev_charging: true,
    turnkey: true,
    days_on_market: 4,
    image: "/assets/images/evergreen_home.png",
    description: "Nestled in the prestigious Evergreen foothills, this gorgeous modern residence offers a spectacular layout. Featuring high ceilings, double pane energy-efficient windows, a fully paid 6.2 kW solar system, and an EV charging outlet in the 2-car garage. Bright and open kitchen with premium Quartz countertops and walk-in pantry. Excellent turnkey condition and top-tier San Jose schools make this a highly sought-after family home."
  },
  {
    id: 2,
    title: "Silver Creek Valley Luxury Estate",
    neighborhood: "Silver Creek",
    price: 3200000,
    beds: 5,
    baths: 6,
    sqft: 5200,
    type: "House",
    status: "Buy",
    school_rating: 8,
    school_details: "Silver Creek Elementary, Chaboya Middle, Silver Creek High (8/10)",
    commute_times: { apple: 28, google: 32, nvidia: 25, adobe: 18 },
    solar: true,
    ev_charging: true,
    turnkey: true,
    days_on_market: 9,
    image: "/assets/images/silver_creek_estate.png",
    description: "Located within the gated enclave of Silver Creek Valley Country Club, this custom Mediterranean estate defines Silicon Valley luxury. Panoramic foothill and city lights views greet you from floor-to-ceiling windows. Featuring a designer chef's kitchen, a private home theatre, dynamic automation controls, and paid solar panels. The sprawling resort-like backyard hosts an infinity edge pool and fireplace pavilion."
  },
  {
    id: 3,
    title: "Willow Glen Craftsman Bungalow",
    neighborhood: "Willow Glen",
    price: 1650000,
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: "House",
    status: "Buy",
    school_rating: 8,
    school_details: "Willow Glen Elementary, Willow Glen Middle, Willow Glen High (8/10)",
    commute_times: { apple: 18, google: 22, nvidia: 16, adobe: 10 },
    solar: true,
    ev_charging: false,
    turnkey: true,
    days_on_market: 2,
    image: "/assets/images/willow_glen_craftsman.png",
    description: "A rare opportunity to own a charming, fully renovated craftsman bungalow walking distance to Downtown Willow Glen shops and dining. Classic design elements including a broad front porch, redwood framing, and hardwood floors are paired with modern comforts: smart climate controls, updated electrical/plumbing, and solar power. Private backyard with mature fruit trees."
  },
  {
    id: 4,
    title: "North San Jose Tech High-Rise",
    neighborhood: "North San Jose",
    price: 780000,
    beds: 2,
    baths: 2,
    sqft: 1150,
    type: "Condo",
    status: "Buy",
    school_rating: 7,
    school_details: "Vinci Park Elementary, Orchard Middle, Independence High (7/10)",
    commute_times: { apple: 15, google: 12, nvidia: 8, adobe: 8 },
    solar: false,
    ev_charging: true,
    turnkey: true,
    days_on_market: 11,
    image: "/assets/images/north_sj_condo.png",
    description: "Perfect for tech professionals looking for a modern, low-maintenance urban home. Situated in the heart of North San Jose, this contemporary high-rise condo features floor-to-ceiling windows, modern concrete columns, and premium kitchen appliances. EV chargers are shared in the secure parking garage. Walking distance to VTA light rail and directly across from major tech headquarters."
  },
  {
    id: 5,
    title: "Almaden Valley Foothills Ranch",
    neighborhood: "Almaden Valley",
    price: 5500,
    beds: 4,
    baths: 3,
    sqft: 2600,
    type: "House",
    status: "Rent",
    school_rating: 9,
    school_details: "Simonds Elementary, Castillero Middle, Leland High (9/10)",
    commute_times: { apple: 22, google: 26, nvidia: 25, adobe: 16 },
    solar: true,
    ev_charging: true,
    turnkey: true,
    days_on_market: 5,
    image: "/assets/images/almaden_valley_home.png",
    description: "Available for lease: a spacious, mid-century modern ranch style villa in highly desirable Almaden Valley. Boasting top-tier schools (including Leland High), a huge flat backyard surrounded by mature redwood trees, and direct access to hiking trails. Fully updated kitchen, solar panels, and EV charging station in the garage. Lease terms available from 12 to 36 months."
  },
  {
    id: 6,
    title: "Cupertino Executive Townhome",
    neighborhood: "Cupertino",
    price: 6200,
    beds: 3,
    baths: 2.5,
    sqft: 1950,
    type: "Townhouse",
    status: "Rent",
    school_rating: 10,
    school_details: "Garden Gate Elementary, Lawson Middle, Monta Vista High (10/10)",
    commute_times: { apple: 3, google: 10, nvidia: 12, adobe: 14 },
    solar: true,
    ev_charging: true,
    turnkey: true,
    days_on_market: 3,
    image: "/assets/images/cupertino_townhouse.png",
    description: "Premium executive townhome for lease in prime Cupertino. Unbeatable location, less than 5 minutes to Apple Park. Modern design features cedar accents, open-concept living room, stainless appliances, solar energy panels, and a level-2 EV outlet. Steps from parks, shopping centers, and walking trails. Zoned for top-rated Monta Vista High school."
  },
  {
    id: 7,
    title: "Downtown San Jose Skyline Penthouse",
    neighborhood: "Downtown San Jose",
    price: 3800,
    beds: 1,
    baths: 1.5,
    sqft: 950,
    type: "Condo",
    status: "Rent",
    school_rating: 6,
    school_details: "Horace Mann Elementary, Burnett Middle, San Jose High (6/10)",
    commute_times: { apple: 16, google: 15, nvidia: 12, adobe: 2 },
    solar: false,
    ev_charging: true,
    turnkey: true,
    days_on_market: 14,
    image: "/assets/images/downtown_penthouse.png",
    description: "Live above it all in this spectacular luxury penthouse in Downtown San Jose. Features floor-to-ceiling windows with twilight views of the skyline and surrounding mountains. Walking distance to Adobe headquarters, Zoom, and the planned Google Diridon campus. Modern designer furniture, LEED certified building amenities, EV-capable parking space, and 24-hour concierge services."
  },
  {
    id: 8,
    title: "Stunning Cambrian Upgraded Family Home",
    neighborhood: "Cambrian / San Jose",
    price: 2399000,
    beds: 4,
    baths: 3,
    sqft: 1671,
    type: "House",
    status: "Buy",
    school_rating: 9,
    school_details: "Union School District: Carlton Elementary, Union Middle, Leigh High (9/10)",
    commute_times: { apple: 18, google: 22, nvidia: 20, adobe: 12 },
    solar: false,
    ev_charging: false,
    turnkey: true,
    days_on_market: 1,
    image: "https://search.mlslistings.com/MediaServer/GetMedia.ashx?Key=3014871579&TableID=9&Type=1&Number=0&Size=2&exk=3b10f352ca2b5fdb29fcf6f07d295747",
    images: ["https://search.mlslistings.com/MediaServer/GetMedia.ashx?Key=3014871579&TableID=9&Type=1&Number=0&Size=2&exk=3b10f352ca2b5fdb29fcf6f07d295747"],
    description: "Stunning 1993-built home in the top-rated Union School District where over $120K in recent upgrades has transformed it into a modern masterpiece. The bright and open floor plan boasts high ceilings, premium flooring, custom lighting, and gourmet chef's kitchen. Located on a quiet cul-de-sac with beautiful curb appeal, private backyard, and easy access to top parks, dining, and Silicon Valley commuter routes."
  }
];

export const defaultTours: TourRequest[] = [
  {
    id: 1,
    property: "Silver Creek Valley Luxury Estate",
    client: "Priya Patel",
    phone: "(408) 555-0192",
    date: "Saturday, June 20, 2:00 PM",
    time: "2 hours ago",
    notes: "Interested in seeing the panoramic valley views and the infinity pool. Pre-approved for $3.5M.",
    status: "Pending"
  },
  {
    id: 2,
    property: "Evergreen Foothills Family Home",
    client: "David Kim",
    phone: "(650) 555-9831",
    date: "Sunday, June 21, 11:00 AM",
    time: "5 hours ago",
    notes: "We have two young kids so we want to confirm details about the nearby Evergreen High School rating.",
    status: "Pending"
  }
];

export const defaultSellers: SellerLead[] = [
  {
    id: 1,
    name: "Marcus Brody",
    email: "m.brody@almaden.com",
    address: "1234 Silver Creek Road, Almaden Valley",
    type: "House",
    beds: 4,
    baths: 3,
    sqft: 2600,
    solar: true,
    ev: true,
    turnkey: true,
    time: "1 day ago",
    notes: "Looking to list our 4-bedroom ranch style villa. House has fully paid solar panels. Need an estimate.",
    status: "Pending"
  }
];
